### ISSUE TITLE
Final Post-N@TM Ticket

### ISSUE THREAD

**Issue by Akshay-Rohatgi** [raad1masum/Drain-Gang#14]
**5 points PBL Final Seed :**

- [x] Presence and involvement at the N@tM on June 1st from 6:00PM to 7:30PM [natm-recap](https://akshayrohatgi.com/drain-jekyll/posts/natm-recap/)
- [x] General day to day activity in classroom: engaged, eager, effort

**20 Points - Meeting Tech Guidelines**
- [x] Individual Assignments and Completion 

- [Akshay Assigned Tickets](https://github.com/raad1masum/Drain-Gang/issues/assigned/Akshay-Rohatgi)
- [Raadwan Assigned Tickets](https://github.com/raad1masum/Drain-Gang/issues/assigned/raad1masum)
- [Alvin Assigned Tickets](https://github.com/raad1masum/Drain-Gang/issues/assigned/alvinzhengq)
- [Jagroop Assigned Tickets](https://github.com/raad1masum/Drain-Gang/issues/assigned/LordRoop)

- [x] Requirements verified and accepted by the sponsor [requirements verified & accepted](https://akshayrohatgi.com/drain-jekyll/posts/project-owner-requirements-review/)
- [x] Presentation at the N@tM [natm-recap](https://akshayrohatgi.com/drain-jekyll/posts/natm-recap/)
- [x] Presentation and requirement completion provided to the teacher (Thu 6/2, Fri 6/3 for Seniors)
- [x] 1 minute commercial video on project (advertise your accomplishments) [link](https://drive.google.com/file/d/1BTcg4XbGVWMrFGuZPL2KZ6k5Jij5QOO7/view?usp=sharing)

**5 Points: Meeting new tech requirements**

**_New Tech Requirements include..._**
- [x]  Database with multiple tables (https://github.com/raad1masum/Drain-Gang/issues/10)
- [x]  Authentication and authorization controls (https://github.com/raad1masum/Drain-Gang/issues/12)
- [x]  Meaningful Capture (ex: notes/upload and associated tables) (https://github.com/raad1masum/Drain-Gang/issues/10, https://github.com/raad1masum/Drain-Gang/issues/8)
- [x] Creativity and applications of new Tech feature features to Sponsor Project
- [x] Not adding distracting features for Sponsor theme, ie non-applicable games, non-applicable fun zones

**5 Points: Teacher Final Assessment**

**_Documentation of Individual Tech Requirements (GitHub Pages)_**
- [x] Showing Success/Achievement
- [ ] Self Grade Assessment (Total: Individual and Team)

**_Documentation of Project, Meeting Tech Guidelines (GitHub Pages)_**
- [x] Showing Engagement (Tickets, Scrum Board) [issues](https://github.com/raad1masum/Drain-Gang/issues), [scrum board](https://github.com/raad1masum/Drain-Gang/projects/1)
- [x] Maintaining Master Plan, [master plan](https://akshayrohatgi.com/drain-jekyll/posts/master-plan/)
- [x] Sponsor Assessment (GitHub Pages) [sponsor verification](https://akshayrohatgi.com/drain-jekyll/posts/project-owner-requirements-review/)
- [ ] Team Assessment (Team Score)
